### ISSUE TITLE
Do you copy from https://github.com/VictorChow/KotlinAndroidLib?

### ISSUE THREAD

**Issue by VictorChow** [ravidsrk/kotlinextensions.com#13]
Do you copy from https://github.com/VictorChow/KotlinAndroidLib?
Fuck copy!

**Comment by FioneraGH** [comment]
Any similarity is purely coincidental, funny.

**Comment by paranoiaaa** [comment]
copy dog !

**Comment by ravidsrk** [comment]
@VictorChow I have added credits to each and every extension taken from your repo.
